spring:
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages.properties
    encoding: UTF-8
    cache-duration: PT1M
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 729d43e4384619b249c7ea0938e206f3
            client-secret: BHLom9HypFmQlORR76tFx7UAGjSPryoA
            scope: profile_nickname, profile_image
            redirect-uri: http://localhost:8080/login/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  header: token
  issuer: prgrms
  client-secret: EDCOFGJ23dlckejwidlc01dkdjvncebnbdivocks293QDDF
  expiry-seconds: 60
